#!/usr/bin/env sh
#MISE description="Login to Azure"

az account get-access-token --tenant $AZURE_TENANT_ID >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Azure session not active. Logging in..."
    az login --tenant $AZURE_TENANT_ID
else
    echo "Azure session already active"
fi
