#!/usr/bin/env sh
#MISE description = "Run terrabutler all-sites on current environment"
#MISE raw=true
#MISE hide=true

for site in $(mise cfg get vars.sites); do
  terrabutler tf -site $site apply
done
