#!/usr/bin/env bash
#MISE description="Run terrabutler for a single site on all environments"
#MISE raw=true
#USAGE arg "<site>" help="Site to run on all environments" {}
#USAGE arg "<action>" default="apply" help="Terrabutler action to perform" {}

set -eu

_failed_envs=""
for env in $(mise cfg get vars.environments); do
    echo "[DEBUG] Setting Terrabutler env to ${env}"
    terrabutler env select "${env}"

    set +e
    terrabutler tf -site "${usage_site}" "${usage_action}"
    _tb_exit_code=$?
    set -e

    if [ $_tb_exit_code -ne 0 ]; then
        echo "[ERROR] An error ocurred when action:${usage_action} on site:${usage_site}."
        _failed_envs="${_failed_envs} ${env}"

        [[ ${TB_MISE_CONTINUE_ON_ERROR:-no} == "yes" ]] && continue
        read -p "Do you want to continue with ALL remaining envs on error? [Yn]" -n 1 -r ; echo
        [[ $REPLY =~ ^[Nn] ]] && exit 42
        TB_MISE_CONTINUE_ON_ERROR=yes
    fi
done

if [[ $_failed_envs != "" ]]; then
    echo
    echo "############################################################################"
    echo "[ERROR] Not all environments run successfully. Errors on the following envs:"
    echo "       ${_failed_envs}"
    echo "############################################################################"
    exit 43
fi
