#!/usr/bin/env bash
#MISE description="Run terrabutler for a single site on all environments"
#MISE raw=true
#USAGE arg "<site>" help="Site to run on all environments" {}
#USAGE arg "<action>" default="apply" help="Terrabutler action to perform" {}

set -eu

for env in $(mise cfg get vars.environments); do
    terrabutler env select "${env}"
    terrabutler tf -site "${usage_site}" "${usage_action}"
done
