#!/usr/bin/env sh
#MISE description="Login to Azure"

set -eu

if az account get-access-token --tenant "$AZURE_TENANT_ID" >/dev/null 2>&1; then
    echo "Azure session already active"
else
    echo "Azure session not active. Logging in..."
    az login --tenant "$AZURE_TENANT_ID"
fi
